module.exports = function(grunt) {

	// Folder settings
	var SOURCES = "source/";

	var SOURCES_JS = SOURCES+"js/";
	var SOURCES_SASS = SOURCES+"sass/";

	var COMPILED = "public/";
	var COMPILED_JS = COMPILED+"js/";
	var COMPILED_SASS = COMPILED+"css/";


	// JS Files
	var JS_PREFIX = "App";
	var JS_FILES = [
		'global',
		'view',
		'api',
		'tools'
	];

	// Fotmat JS Array
	for(var i in JS_FILES){
		JS_FILES[i] = SOURCES_JS+JS_PREFIX+"."+JS_FILES[i]+".js"
	}

	grunt.initConfig({

		// Compile Sass with Compass
		compass: {
			dist: {
			  options: {
			    sassDir: SOURCES_SASS,
			    cssDir: COMPILED_SASS,
			    environment: 'production',
			    specify: [SOURCES_SASS+'main.scss']
			  }
			}
		},

		// JSHint
		jshint: {
			files: [SOURCES_JS+'/*.js'],
			options: {
				laxcomma: true,
				boss: true,
				curly: true,
				eqeqeq: true,
				eqnull: true,
				es3: true,
				browser: true,
				smarttabs: true,
				"-W099": true, // Relax rules on mixed tabs and spaces
				globals: {
					jQuery: true
				}
			}
		},

		// Concatatenated Javascript
		concat: {
			options: {
				banner: '/*! DO NOT EDIT THIS FILE */\n'+'/*! File Concatatenated by grunt @ <%= grunt.template.today("yyyy-mm-dd HH:MM") %> */\n'
			},
			js: {
				src: JS_FILES,
				dest: COMPILED_JS+'app.js'
			}
		},

		// Minified Javascript
		uglify: {
		  options: {
		    banner: '/*! DO NOT EDIT THIS FILE */\n'+'/*! File Minified by grunt @ <%= grunt.template.today("yyyy-mm-dd HH:MM") %> */\n',
			mangle: false
		  },
		  build: {
		    src: COMPILED_JS+'app.js',
		    dest: COMPILED_JS+'app.min.js'
		  }
		},

		// Watch files and build when they change
		watch: {
			css: {
				files: [SOURCES_SASS+'*.scss', SOURCES_SASS+'/mixins/*.scss'],
				tasks: ['compass'],
				options: {
				    // Start a live reload server on the default port 35729
				    livereload: true,
				}
			},
			js: {
				files: [SOURCES_JS+'*.js'],
				tasks: ['jshint','concat', 'uglify']
			}
		},

		notify_hooks: {
			options: {
				enabled: true,
				max_jshint_notifications: 2, // maximum number of notifications from jshint output
				title: "Oops!" // defaults to the name in package.json, or uses project's directory name, you can change to the name of your project
			}
		}

	});

	// Load grunt different tasks
	grunt.loadNpmTasks('grunt-contrib-concat');
	grunt.loadNpmTasks('grunt-contrib-uglify');
    grunt.loadNpmTasks('grunt-contrib-watch');
    grunt.loadNpmTasks('grunt-contrib-compass');
    grunt.loadNpmTasks('grunt-contrib-jshint');
    grunt.loadNpmTasks('grunt-notify');
	grunt.task.run('notify_hooks');
	// Register grunt tasks
    grunt.registerTask('default', ['jshint', 'concat', 'uglify', 'compass', 'watch', 'notify:watch']);

};